Repository hmcts/wa-task-management-api, pull requests merged in 2023-08, with the labels that each got.

#1139 RWA-2693: Fix CVE-2023-34034
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1139

#1141 Correcting wal_level requirements
  infrastructure/main.tf
  src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReportingService.java
  src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReportingServiceTest.java
Labels: ns:wa, prd:wa, add-or-update, rel:wa-task-management-api-pr-1141

#1144 Flexible server replica-2 - AAT only
  infrastructure/main.tf
Labels: ns:wa, prd:wa, add-or-update, rel:wa-task-management-api-pr-1144

#1146 test jit in AAT
  infrastructure/main.tf
Labels: ns:wa, prd:wa, destroy, rel:wa-task-management-api-pr-1146

#1149 RWA-2712 delete API modification
  src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagerDeleteTaskProviderTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/DeleteTasksControllerTest.java
  src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/restrict/ClientAccessControlService.java
  src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskActionsController.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/restrict/ClientAccessControlServiceTest.java
  src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskActionsControllerTest.java
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1149, keep-helm

#1153 RWA-2712 revert changes
  src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagerDeleteTaskProviderTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/DeleteTasksControllerTest.java
  src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/restrict/ClientAccessControlService.java
  src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskActionsController.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/restrict/ClientAccessControlServiceTest.java
  src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskActionsControllerTest.java
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1153

#1155 RWA-2750 Fix CVE-2023-20883 Fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1155
