Repository hmcts/wa-task-management-api, pull requests merged in 2023-11, with the labels that each got.

#1185 RWA-2347: added flexmark repository to build
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1185

#1189 RWA-2870: Update publishResults settings in build.gradle
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1189

#1184 RWA-2905 - Added SQL data fixes
  src/main/resources/scripts/rwa-2905_update_civil_role_categories.sql
  src/main/resources/scripts/rwa-2905_update_civil_role_categories_rollback.sql
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1184

#1190 Rwa 2829
  src/main/resources/scripts/rwa-2829_mi_data_fix_checks_all_jurisdictions.sql
  src/main/resources/scripts/rwa-2829_mi_data_fixes_civil_and_privatelaw.sql
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1190

#1191 Rwa 2829 1
  src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/db/MIReplicaDBDao.java
  src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReplicaReportingServiceTest.java
  src/main/resources/dbreplica/migration/V1.0.24__mark_tasks_for_refresh.sql
  src/main/resources/scripts/rwa-2943_mi_data_fixes_ia.sql
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1191
