Repository hmcts/wa-task-management-api, pull requests merged in 2023-12, with the labels that each got.

#1195 RWA-2994: Fix CVE
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1195

#1198 RWA-3020: upgrade owasp version
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1198

#1197 RWA-2998 - Drop constraints in replica database
  src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReplicaReportingServiceTest.java
  src/main/resources/dbreplica/migration/V1.0.25__drop_unnecessary_constraint_replica.sql
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1197
