Repository hmcts/wa-task-management-api, pull requests merged in 2024-01, with the labels that each got.

#1006 cleanup
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1006

#1200 Nuking legacy TM DB resources
  infrastructure/main.tf
Labels: ns:wa, prd:wa, destroy, rel:wa-task-management-api-pr-1200

#1203 Add all attributes used by TM for from the AM queryAssignment endpoin…
  src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/wataskconfigurationapi/consumer/roleassignment/RoleAssignmentQueryConsumerTest.java
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1203

#1204 changed to testImplementation
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1204

#1212 commented out aggregate
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1212

#1213 RWA-3079 Jenkins Nightly failure fix
  Jenkinsfile_nightly
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1213

#1215 Refactoring in order to republish provider to pact broker
  src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagementGetTaskRolePermissionsTest.java
  src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/WorkTypeProviderTest.java
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1215

#1214 RWA-3083 initial fix
  src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskExecuteReconfigureControllerTest.java
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1214

#1216 RWA-2975 added additional log
  src/main/resources/dbreplica/migration/V1.0.26__task_history_plsql.sql
  src/main/resources/dbreplica/migration/V1.0.27__reportable_task_plsql.sql
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1216

#1217 RWA-3087: fix cve issues
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1217
