Repository hmcts/wa-task-management-api, pull requests merged in 2024-07, with the labels that each got.

#1266 RWA-3485: Define DockerImageName
  src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/db/PostgreExtendedSQLContainerProvider.java
  src/integrationTest/resources/application-integration.yaml
  src/integrationTest/resources/application-replica.yaml
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1266

#1268 Revert "RWA-3485: Define DockerImageName"
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/db/PostgreExtendedSQLContainerProvider.java
  src/integrationTest/resources/application-integration.yaml
  src/integrationTest/resources/application-replica.yaml
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1268

#1269 RWA-3494: Extend suppressions
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1269

#1267 Adding more fine tuning for renovate PRs
  .github/renovate.json
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1267

#1265 RWA:3471: Bump dependencies for Spring boot upgrade
  build.gradle
Labels: ns:wa, prd:wa, WIP, rel:wa-task-management-api-pr-1265
