Repository hmcts/wa-task-management-api, pull requests merged in 2024-06, with the labels that each got.

#1259 RWA-2482: Non Prod task cleanup scripts
  src/main/resources/scripts/cleanup/non_prod_primary_and_replica_data_cleanup.sql
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1259

#1262 RWA-3384: Extend Suppressions
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1262

#1263 remove dependabot config
  .github/dependabot.yml
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1263
