Repository hmcts/wa-task-management-api, pull requests merged in 2024-05, with the labels that each got.

#1257 RWA-3201 Update ET Service name
  src/main/resources/dbreplica/migration/V1.0.33__reportable_task_plsql.sql
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1257

#1258 Rwa 2903
  src/main/resources/scripts/rwa-2903_update_civil_role_categories_work_types.sql
  src/main/resources/scripts/rwa-2903_update_civil_role_categories_work_types_rollback.sql
  src/main/resources/scripts/rwa-2903_update_iac_role_categories_work_types.sql
  src/main/resources/scripts/rwa-2903_update_iac_role_categories_work_types_rollback.sql
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1258

#1256 RWA-3307 Race condition with async Reconfigurations and Terminations
  src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/ExecuteReconfigurationTaskOperationControllerTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/MarkReconfigurationTaskOperationControllerTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/repository/TaskResourceRepositoryTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTTaskDatabaseServiceTest.java
  src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/repository/TaskResourceRepository.java
  src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTTaskDatabaseService.java
  src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/operation/ExecuteTaskReconfigurationService.java
  src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/operation/MarkTaskReconfigurationService.java
  src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTTaskDatabaseServiceTest.java
  src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/operation/ExecuteTaskReconfigurationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/operation/MarkTaskReconfigurationServiceTest.java
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1256

#1260 Upgrade terraform
  infrastructure/.terraform-version
Labels: ns:wa, prd:wa, aat/destroy, prod/destroy, rel:wa-task-management-api-pr-1260

#1247 RWA-3199 MI Reporting: Power BI Prod shows a "Blank" option - Backend…
  src/main/resources/scripts/rwa-3199_mi_data_fixes.sql
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1247
