Repository hmcts/wa-task-management-api, pull requests merged in 2025-06, with the labels that each got.

#1442 Add `statement_timeout`
  infrastructure/main.tf
Labels: ns:wa, prd:wa, aat/destroy, prod/destroy, rel:wa-task-management-api-pr-1442

#1434 RWA-4238: Removed hardcoded password
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/functionalTest/resources/application-functional.yaml
  src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/services/AuthorizationProvider.java
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1434

#1443 RWA-4366: Bumping owasp
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1443

#1444 RWA-4405: Improving FT resilience
  src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/SpringBootFunctionalBaseTest.java
  src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/config/GivensBuilder.java
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1444

#1447 RWA-4450: revert pitest
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1447

#1461 CME-722 Replaced JitPack with Azure Artifacts
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1461
