Repository hmcts/wa-task-management-api, pull requests merged in 2025-02, with the labels that each got.

#1377 RWA-4077 updated test and updated API doc
  src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/BaseController.java
  src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/ExclusiveTaskActionsController.java
  src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/operation/TaskReconfigurationTransactionHandlerTest.java
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1377

#1386 Cme 124 db monitoring bump azurerm 4.0
  infrastructure/state.tf
Labels: ns:wa, prd:wa, prod/destroy, aat/add-or-update, rel:wa-task-management-api-pr-1386

#1387 Revert "CME-124 enable DB alerts"
  config/owasp/suppressions.xml
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:wa, prd:wa, aat/destroy, prod/destroy, rel:wa-task-management-api-pr-1387

#1375 RWA-3970 validation
  src/functionalTest/resources/application-functional.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/newinitiate/PostInitiateByIdControllerTest.java
  src/integrationTest/resources/application-integration.yaml
  src/integrationTest/resources/application-replica.yaml
  src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/ExclusiveTaskActionsController.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/ExclusiveTaskActionsControllerTest.java
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1375

#1378 CME-349: Upgrade AzureRM
  infrastructure/state.tf
Labels: ns:wa, prd:wa, aat/destroy, prod/destroy, rel:wa-task-management-api-pr-1378

#1391 Update Jenkinsfile_CNP
  Jenkinsfile_CNP
Labels: ns:wa, prd:wa, rel:wa-task-management-api-pr-1391

#1389 Cme 124 test db monitoring
  config/owasp/suppressions.xml
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:wa, prd:wa, aat/destroy, ithc/destroy, rel:wa-task-management-api-pr-1389
